language: node_js
node_js:
  - "7"
cache:
  directories:
    - "node_modules"
script:
  - npm test
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - npm run lint
  - npm run build
deploy:
  provider: firebase
  skip_cleanup: true
  token: ${FIREBASE_TOKEN}
  on:
    branch: master
  
    
